name:  example
description: An example app for line_awesome_flutter package.

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # line_awesome_flutter: ^1.0.0
  line_awesome_flutter:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
